### ISSUE TITLE
Hands and digital time/date not showing when in horizontal/vertical stack

### ISSUE THREAD

**Issue by busiderbaer** [tomasrudh/analogclock#28]
Hi,
my plan was to use a analog clock in a horizontal stack. However, I ran into an issue where there are no hands and no digital time/date shown when in a horizontal or vertical stack or grid. It does work without the stack and in the lovelace-layout-card (https://github.com/thomasloven/lovelace-layout-card).
I cleared the cache of my browser (Firefox 106.0.1 on Win 10 64-bit) multiple times to no avail. The Moment resource is installed according to your readme.

Here are my .yaml codes and corresponding behaviour:

```
type: horizontal-stack
cards:
  - type: custom:analog-clock
    hide_minorticks: true
    hide_secondhand: true
    style_hourhand: 3
    style_minutehand: 3
    diameter: 150
  - type: thermostat
    entity: climate.thermostat_hc1
```

![Screenshot 2022-10-25 at 10-57-31 Tablet – Home Assistant](https://user-images.githubusercontent.com/56730355/197735380-02a0bee4-0c0c-40f3-ba70-a040915ac9eb.png)

```
type: custom:layout-card
layout_type: custom:horizontal-layout
layout:
  width: 180
cards:
  - type: thermostat
    entity: climate.thermostat_hc1
  - type: custom:analog-clock
    hide_minorticks: true
    hide_secondhand: true
    style_hourhand: 3
    style_minutehand: 3
    diameter: 150
```

![Screenshot 2022-10-25 at 11-15-21 Tablet – Home Assistant](https://user-images.githubusercontent.com/56730355/197735692-39700e33-d90c-4ee7-b2c3-a186bb01e479.png)

If you need anything else or if I miss something, please let me know.
